ðŸ”„ Starting training with config: {'activation': 'sigmoid', 'batch_size': 64, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'dataset': 'fashion_mnist', 'epochs': 5, 'epsilon': 1e-08, 'hidden_size': 32, 'learning_rate': 0.001, 'loss': 'mean_squared_error', 'momentum': 0.9, 'num_layers': 5, 'optimizer': 'nag', 'weight_decay': 0.0005, 'weight_init': 'random'}
Epoch 1/5 - loss: 0.4500 - accuracy: 0.0998 - val_loss: 0.4500 - val_accuracy: 0.1013
Epoch 2/5 - loss: 0.4500 - accuracy: 0.0997 - val_loss: 0.4500 - val_accuracy: 0.0933
Epoch 3/5 - loss: 0.4500 - accuracy: 0.1004 - val_loss: 0.4500 - val_accuracy: 0.0933
Epoch 4/5 - loss: 0.4500 - accuracy: 0.0987 - val_loss: 0.4500 - val_accuracy: 0.0933
Epoch 5/5 - loss: 0.4500 - accuracy: 0.1000 - val_loss: 0.4500 - val_accuracy: 0.0933
Test loss: 0.4500 - Test accuracy: 0.1000
K:\DA6401\da6401_assignment1\train.py:117: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure(figsize=(10, 8))
K:\DA6401\da6401_assignment1\train.py:269: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig, axs = plt.subplots(2, 5, figsize=(12, 6))
